package com.noddy.statussaver.utils

object SharedPrefKeys {
    const val PREF_KEY_WP_PERMISSION_GRANTED = "PREF_KEY_PERMISSION_GRANTED"
    const val PREF_KEY_WP_TREE_URI = "PREF_KEY_TREE_URI"
    const val PREF_KEY_WP_BUSINESS_PERMISSION_GRANTED = "PREF_KEY_WP_BUSINESS_PERMISSION_GRANTED"
    const val PREF_KEY_WP_BUSINESS_TREE_URI = "PREF_KEY_WP_BUSINESS_TREE_URI"
    const val PREF_KEY_IS_PERMISSIONS_GRANTED = "PREF_KEY_IS_PERMISSIONS_GRANTED"
    const val PREF_AUTO_CLEAN = "PREF_AUTO_CLEAN"
    const val PREF_SORT_TYPE = "PREF_SORT_TYPE"
    const val PREF_APP_LOCK_ENABLED = "PREF_APP_LOCK_ENABLED"
    const val PREF_APP_LOCK_PIN = "PREF_APP_LOCK_PIN"
}